FROM nginx:1.25.2-alpine

RUN rm /etc/nginx/conf.d/default.conf

COPY ./nginx.conf /etc/nginx/nginx.conf
COPY ./security-headers.conf /etc/nginx/security-headers.conf
COPY ./options-ssl-nginx.conf /etc/nginx/options-ssl-nginx.conf
COPY ./ssl-dhparams.pem /etc/nginx/ssl-dhparams.pem
