add_header Strict-Transport-Security "max-age=31449600; includeSubDomains" always;
# DOMAIN has to be set in NGINX conf to the domain that this site is being
# served from. This is used in the Content-Security-Policy header to allow
# images, scripts, and styles to be loaded from the domain. If you want to allow
# requests to other subdomains, such as api.example.com, replace ${DOMAIN}
# with *.example.com in the CSP header below.
add_header Content-Security-Policy "default-src 'self'; object-src 'none'; img-src 'self' blob: data: ${DOMAIN} *.digitaloceanspaces.com; script-src 'self' 'unsafe-inline' ${DOMAIN} www.google.com www.gstatic.com www.googletagmanager.com; style-src 'self' 'unsafe-inline' ${DOMAIN} fonts.googleapis.com cdn.jsdelivr.net; font-src 'self' fonts.gstatic.com cdn.jsdelivr.net; connect-src 'self' blob: data: ${DOMAIN} *.digitaloceanspaces.com www.google-analytics.com www.google.com www.gstatic.com www.recaptcha.net cdn.jsdelivr.net;" always;
add_header X-Frame-Options "DENY" always;	
add_header X-Content-Type-Options "nosniff" always;
add_header Referrer-Policy "strict-origin" always;
add_header Permissions-Policy "geolocation=(self), microphone=(self), camera=(self)" always;
